baseURL: "https://jeremiahxing.github.io/blog/"
title: Jeremiah's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Jeremiah's Blog
  description: "Jeremiah's Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Jeremiah Hsing
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShareButtons: ["linkedin", "x", "facebook", "twitter", "whatsapp", "telegram", "reddit"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-touch-icon.png"
    safari_pinned_tab: "icons/favicon.ico"

  label:
    text: "Home"
    icon: icons/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Jeremiah's Blog
    subtitle: "Tech with a Touch of Zen"
    imageUrl: "images/avatar.png"
    imageWidth: 80
    imageHeight: 80
    imageTitle: avatar
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: I'm Jeremiah, welcome to my blog :)

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/jeremiahhsing/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/16084078/jeremiah"
    - name: github
      url: "https://github.com/JeremiahXing"

  analytics:
    google:
      SiteVerificationTag: "XYZabc" # please change this to your own
    bing:
      SiteVerificationTag: "XYZabc" # please change this to your own
    yandex:
      SiteVerificationTag: "XYZabc" # please change this to your own

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/JeremiahXing/blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: Tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: Archives
      name: archives
      url: /archives/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary for search

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod